env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "8"
  - "node"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng12-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8

after_success: npm run coverage
